schedule :
   jobs :
    -
      cronExpression : 0/7 * * * * * ? 
      scheduledDate : 2017/03/02 17:03:00
      dataToWrite : first job
    -
      cronExpression :  0/10 * * * * * ?
      scheduledDate : 2017/03/02 17:07:00
      dataToWrite : second job
    -
      cronExpression :  0 * * * * * ?
      scheduledDate : 2017/03/02 17:06:45
      dataToWrite : Third job
    -
      cronExpression :  0 * * * * * ?
      scheduledDate : 2017/03/02 17:05:30
      dataToWrite : Fourth job      